---
simulation:
  iterations: 1000
objectives: 1
config: 0
environment:
  width: 20
  height: 20
resources:
  small:
    width: 1.0
    height: 1.0
    mass: 1.0
    pushingBots: 1
    type: A
  medium:
    width: 1.0
    height: 1.0
    mass: 5.0
    pushingBots: 2
    type: B
  large:
    width: 1.0
    height: 1.0
    mass: 10.0
    pushingBots: 3
    type: C
scoring:
  fitnessFunction: za.redbridge.simulator.ea.DefaultFitnessFunction
factories:
  resourceFactory: za.redbridge.simulator.factories.ConfigurableResourceFactory
  robotFactory: za.redbridge.simulator.factories.HomogeneousRobotFactory
robots:
  numRobots: 15
  mass: 0.7
  radius: 0.15
  colour: 0, 0, 0
